# Generated by Django 5.2 on 2025-04-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code (e.g., US, GB, CA).', max_length=2, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description (e.g., United States).', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Geofence Allowed Country',
                'verbose_name_plural': 'Geofence Allowed Countries',
                'ordering': ['country_code'],
            },
        ),
    ]
