# Generated by Django 5.2 on 2025-04-21 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_geofencerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortSpecificDDoSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField(help_text='The specific network port number (1-65535).', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('time_window_seconds', models.PositiveIntegerField(default=60, help_text='Time window in seconds for this specific port.')),
                ('request_threshold', models.PositiveIntegerField(default=50, help_text='Max requests per IP in the time window for this specific port.')),
                ('description', models.CharField(blank=True, help_text='Optional description (e.g., SSH Port, Web Login).', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/Disable rule for this specific port.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Port-Specific DDoS Rule',
                'verbose_name_plural': 'Port-Specific DDoS Rules',
                'ordering': ['port'],
            },
        ),
        migrations.AlterModelOptions(
            name='ddosconfig',
            options={'verbose_name': 'Default DDoS Configuration', 'verbose_name_plural': 'Default DDoS Configuration'},
        ),
        migrations.RemoveField(
            model_name='ddosconfig',
            name='request_threshold',
        ),
        migrations.RemoveField(
            model_name='ddosconfig',
            name='time_window_seconds',
        ),
        migrations.AddField(
            model_name='ddosconfig',
            name='default_request_threshold',
            field=models.PositiveIntegerField(default=100, help_text='Default max requests per IP in the time window (if no port-specific rule matches).'),
        ),
        migrations.AddField(
            model_name='ddosconfig',
            name='default_time_window_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Default time window in seconds for rate limiting.'),
        ),
        migrations.AlterField(
            model_name='ddosconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable/Disable all DDoS detection.'),
        ),
    ]
