# Generated by Django 5.2 on 2025-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_portspecificddosconfig_alter_ddosconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqlipattern',
            options={'ordering': ['description'], 'verbose_name': 'SQL Injection Pattern', 'verbose_name_plural': 'SQL Injection Patterns'},
        ),
        migrations.AddField(
            model_name='ddosconfig',
            name='global_rate_threshold',
            field=models.PositiveIntegerField(default=5000, help_text='Max total incoming packets per second to the server before alerting.'),
        ),
        migrations.AddField(
            model_name='ddosconfig',
            name='global_rate_window_seconds',
            field=models.PositiveIntegerField(default=10, help_text='Time window in seconds for global rate limit.'),
        ),
        migrations.AddField(
            model_name='ddosconfig',
            name='syn_flood_threshold',
            field=models.PositiveIntegerField(default=50, help_text='Max incoming TCP SYN packets per second from a single source before alerting.'),
        ),
        migrations.AddField(
            model_name='ddosconfig',
            name='syn_flood_window_seconds',
            field=models.PositiveIntegerField(default=10, help_text='Time window in seconds for SYN flood rate limit.'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('SQLI', 'SQL Injection'), ('DDOS', 'DDoS Rate Exceeded')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source_ip',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ddosconfig',
            name='default_request_threshold',
            field=models.PositiveIntegerField(default=100, help_text='Default max requests per IP in the window (if no port-specific rule matches).'),
        ),
    ]
