# Generated by Django 5.2 on 2025-04-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_sqlipattern_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.CharField(blank=True, help_text='Why this IP was blocked (e.g., DDoS, SQLi Attempt, Manual)', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the IP was blocked')),
            ],
            options={
                'verbose_name': 'Blocked IP Address',
                'verbose_name_plural': 'Blocked IP Addresses',
                'ordering': ['-timestamp'],
            },
        ),
    ]
