# Generated by Django 5.2 on 2025-04-23 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_blockedip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('protocol', models.CharField(db_index=True, max_length=10)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True)),
                ('size_bytes', models.PositiveIntegerField()),
                ('source_port', models.PositiveIntegerField(blank=True, null=True)),
                ('tcp_flags', models.CharField(blank=True, max_length=10, null=True)),
                ('related_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.alert')),
            ],
            options={
                'verbose_name': 'Packet Log Entry',
                'verbose_name_plural': 'Packet Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'source_ip'], name='detection_p_timesta_11bcac_idx'), models.Index(fields=['timestamp', 'protocol'], name='detection_p_timesta_11e6c6_idx')],
            },
        ),
    ]
